name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'preddath'
          reponame: 'epoch-talents'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      - run: |
          git config --global user.name "CI"
          git config --global user.email "ci@example.com"
          git fetch
          git switch gh-pages
          sed -i -e 's+/epoch_logo+epoch_logo+g' index.html
          sed -i -e 's+assets+epoch-talents/assets+g' index.html
          git commit -a -m "Fix imports"
          git push