name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'preddath'
          reponame: 'epoch-talents'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        env:
          CI_COMMIT_MESSAGE: Fix imports
          CI_COMMIT_AUTHOR: CI
      - run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "ci@example.com"
          sed -i -e 's+/epoch_logo+epoch_logo+g' index.html
          sed -i -e 's+assets+epoch-talents/assets+g' index.html
          git commit --verbose -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push origin gh-pages